### ISSUE TITLE
Querying using dot notation for nested keys does not provide any results

### ISSUE THREAD

**Issue by cantoine** [LokiJS-Forge/LokiDB#130]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/LokiJS-Forge/LokiDB/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently if I have a record like this:
```
{
  _id: 1,
  key: {
    subkey: 'some sub key 1',
  }
}
```
I can't seem to query for the subkey using any syntax options that I can come up with. I expected this to work with dot notation similar to the original Lokijs or Mongo. An example query would be `collection.findOne( { 'key.subkey': 'some sub key 1' } )`

## Expected behavior
I would expect dot notation to provide a result when querying nested keys.

## Minimal reproduction of the problem with instructions
https://next.plnkr.co/edit/YjcUXu94hbCIVdYv?open=lib%2Fscript.js

## Environment
Node 8.10/Latest Chrome
LokiDB version: 2.0.0-beta.6

**Comment by Viatorus** [comment]
Thank you for your bug report.

In LokiDB the nested property support has been changed and extended to support binary indices and full-text search indicies by adding getter/setter methods to your documents. 

To get your example work, you have to add this to the collection constructor:

```js
nestedProperties: ["key.subkey"]
```
or to make an alias name:
```js
nestedProperties: [{name: "MyNewSubKey", path: ["key", "subkey"]}]
```

**Comment by cantoine** [comment]
Ah, I missed the nested properties option and that does solve the initial question. One additional question in regard to this does/can nestedProperties work for querying object keys nested in an array? Data would be something like this: 
```
{
  _id: _.uniqueId(),
  arrayObjects: [
    {
       _id: _.uniqueId(),
       key: `value ${ i }`
     }
  ]
}```
and the query would be something like `{ 'arrayObjects.key': 'value 1' }`

Thanks!
Chris

**Comment by Viatorus** [comment]
Yes, this should work.

>

**Comment by cantoine** [comment]
That worked perfectly once I figured out how $contains works :-)

Out of curiosity what is the reasoning behind $contains instead of just using the dot notation to find the value? I only ask because finding the value with just dot notation would be more consistent with the mongo api.

Thanks for all of the help!!

**Comment by Viatorus** [comment]
I am glad, that I could help.

Hmm, that is sad, that it differs from the mongo API...
The problem is, that the dot notation is now resolved while inserting a new document to the collection by adding getter and setter to it and not like LokiJS and MongoDB while performing a query:

https://github.com/techfort/LokiJS/blob/f7acb98a4129845bbd2c9aa23e5ed4a10ee75ce8/src/lokijs.js#L335-L360

The advances are:
* Only on place you have to handle dot notations
* The query don`t have to be parsed for dot notations
* Support for nested binary indices and full-text search (but not for ones inside arrays)
* Nested property names don`t have to be dots

The disadvances are:
* If the nested property is inside an array, we return all nested properties as array

Maybe I can fix this disadvances some how...
